### ISSUE TITLE
Ransoming Stars ? 

### ISSUE THREAD

**Issue by mbostwick** [ro31337/bigoposter#4]
It seems harmful to the git hub community to ransom stars ? If your going to make it MIT, then do it, if not why not put it somewhere else other then git hub ? Git hubs greatest tool is the ability to fork, merge, and grow the work. Also, something like this would be better as creative common, as oppose to MIT.. 

It really does look like your just copying @ericdrowell work

**Comment by ro31337** [comment]
I don't really need stars, 2000 was random number, and I didn't expect this will reach even 20 stars. I've just updated repository description title, and will release the source as soon as I can. And don't take stars too seriously :)

I admit that content comes mostly from this source and I'll add a link. But believe me, it was not easy at all to put this into one page, especially when you're developer and have zero knowledge about design tools and how to use them. Moreover, there are also some tricks when it comes to printing. Printing one hundred times and picking the right colors is a lot of work.

So I don't accept your charge that I'm just copying @ericdrowell work. And please do respect others who do hard work for free. You don't contribute to Open Source community at all by saying "hey, you're just copying".
