### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by msbanik** [ro31337/bigoposter#6]
Could you please add the source code.

**Comment by ro31337** [comment]
In 1 week, max 2 weeks, I'll add it. I'm about to finish polishing it.

**Comment by msbanik** [comment]
Cool.

**Comment by OussamaRomdhane** [comment]
Where are we on this issue? :stuck_out_tongue_winking_eye:

**Comment by ro31337** [comment]
Source file added, closing issue.
